# Generated by Django 3.2 on 2021-04-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=2)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('content', models.ImageField(upload_to='content/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ContentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=30)),
                ('meta_value', models.CharField(max_length=120)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.content')),
            ],
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.CheckConstraint(check=models.Q(rating__lte=10.0), name='rating_lte_10.0'),
        ),
        migrations.AddField(
            model_name='channel',
            name='parent_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel', to='main.channel'),
        ),
    ]
